Add job.result, step.outcome, and step.conclusion
typesafegithub/github-workflows-kt pull request #1109
Opened 2023-11-17 11:30 UTC by LouisCAD

Hello!

As discussed in Slack.

Open to concerns and ideas for `AbstractResult`.

Have a great day!

2023-11-18 13:27 UTC, LouisCAD commented
I don't know how to solve this lint thing:
> library/src/test/kotlin/io/github/typesafegithub/workflows/domain/JobTest.kt:19:23: Lint error > [standard:multiline-expression-wrapping] A multiline expression should start on a new line

It looks like a bug, if you know what the problem actually is, or how to disable that check, please go ahead.

2023-11-18 14:03 UTC, krzema12 requested changes

2023-11-18 14:03 UTC, krzema12 commented on library/src/test/kotlin/io/github/typesafegithub/workflows/domain/JobTest.kt
> +        workflow(
Do you need to use the workflow in this test? See the tests below - they use the `Job` domain class directly.

2023-11-18 14:06 UTC, krzema12 commented
> I don't know how to solve this lint thing:
> 
> > library/src/test/kotlin/io/github/typesafegithub/workflows/domain/JobTest.kt:19:23: Lint error > [standard:multiline-expression-wrapping] A multiline expression should start on a new line
> 
> It looks like a bug, if you know what the problem actually is, or how to disable that check, please go ahead.

Just run `formatKotlin` task and ktlint fill fix it for you 😄

2023-11-18 17:08 UTC, LouisCAD commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/AbstractResult.kt
> +    public enum class Status {
I don't see what new states they would add to any of those, but we can always duplicate the old enum and the overloads of `eq` and `neq` using it, and add new enums with new `eq` and `neq` overloads.

2023-11-18 17:24 UTC, LouisCAD commented on library/src/test/kotlin/io/github/typesafegithub/workflows/domain/JobTest.kt
> +        workflow(
I just want to have access to the DSL so I can add steps. Feel free to rewrite if you know how to.

2023-11-18 17:27 UTC, krzema12 commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/AbstractResult.kt
> +    public enum class Status {
Ok, let's leave it as is.

2023-11-18 17:27 UTC, LouisCAD commented on library/src/test/kotlin/io/github/typesafegithub/workflows/domain/JobTest.kt
> +            job.result.eq(Status.Failure) shouldBe "needs.some-id.result == 'failure'"
I think it's still good to test all the API surface, especially if for some reason, we need to branch jobs away from steps.

2023-11-18 17:27 UTC, krzema12 commented on library/src/test/kotlin/io/github/typesafegithub/workflows/domain/JobTest.kt
> +        workflow(
Ok, I'll take care of it.

2023-11-18 17:32 UTC, LouisCAD commented
> Just run `formatKotlin` task and `ktlint` will fix it for you 😄 Issues like this are fortunately auto-fixable.

Okay. I ran it. I think the result is worse, forcing a new line to start a multiline expression is a divergence from Kotlin's official style guidelines, and it increases indentation needlessly IMO.

2023-11-18 17:32 UTC, LouisCAD commented on library/src/test/kotlin/io/github/typesafegithub/workflows/domain/JobTest.kt
> +                step0.outcome.eq(Status.Failure) shouldBe "steps.step-0.outcome == 'failure'"
Done.

2023-11-18 17:36 UTC, krzema12 commented
> > Just run `formatKotlin` task and `ktlint` will fix it for you 😄 Issues like this are fortunately auto-fixable.
> 
> Okay. I ran it. I think the result is worse, forcing a new line to start a multiline expression is a divergence from Kotlin's official style guidelines, and it increases indentation needlessly IMO.

Well, I don't like it as well, but I decided to stick to the style implemented by ktlint for the sake of consistency 😊 We may want to ask the ktlint folks why they decided to format this way, I'd be interested in the rationale.

2023-11-18 17:38 UTC, krzema12 commented on library/src/test/kotlin/io/github/typesafegithub/workflows/domain/JobTest.kt
> +            job.result.eq(Status.Failure) shouldBe "needs.some-id.result == 'failure'"
What do you mean by branching away jobs from steps? Jobs consist of steps.

2023-11-18 17:43 UTC, LouisCAD commented on library/src/test/kotlin/io/github/typesafegithub/workflows/domain/JobTest.kt
> +            job.result.eq(Status.Failure) shouldBe "needs.some-id.result == 'failure'"
I mean, if as mentioned below, there are some changes in GitHub API that mean that job.result and step.outcome or step.conclusion need to be different, having dedicated steps for each use case can be helpful in seeing changing one thing affects others.

However, you can remove it if you feel it's unnecessary or is adding unwanted clutter.

2023-11-19 09:52 UTC, LouisCAD commented on library/src/test/kotlin/io/github/typesafegithub/workflows/domain/JobTest.kt
> +        workflow(
Took another look, and found how to replace this with calls to `CommandStep` and `ActionStep`.

2023-11-19 09:54 UTC, LouisCAD commented on library/src/test/kotlin/io/github/typesafegithub/workflows/domain/JobTest.kt
> +            job.result.eq(Status.Failure) shouldBe "needs.some-id.result == 'failure'"
I rewrote the tests so that tests for `Step` are in their own class (I didn't find a suitable existing one so I created one).

I think this is irrelevant, but I'll let you decide whether to click the "Resolve conversation" button.

2023-11-19 09:57 UTC, LouisCAD commented
Anything blocking this PR now?

2023-11-19 13:00 UTC, krzema12 commented
Thanks, I'll handle it from here, will likely hit the next release.

2023-11-19 18:32 UTC, krzema12 commented on library/src/test/kotlin/io/github/typesafegithub/workflows/domain/JobTest.kt
> +            val job =
Asked about this style on ktlint channel: https://kotlinlang.slack.com/archives/CKS3XG0LS/p1700418701229929

2023-11-19 18:33 UTC, krzema12 commented on library/src/test/kotlin/io/github/typesafegithub/workflows/domain/JobTest.kt
> +            job.result.eq(Status.Failure) shouldBe "needs.some-id.result == 'failure'"
Awesome, thanks!

2023-11-19 18:37 UTC, krzema12 commented
@LouisCAD thanks for closing one of the backlogged tasks #296 😄
And thanks for the contribution overall.

2023-11-19 18:38 UTC, krzema12 approved these changes

2023-11-19 18:41 UTC, merged

2023-11-20 07:20 UTC, LouisCAD commented
Wow, I hadn't realized it was 1 year old! Thanks for accepting my contribution, and thanks to @Vampire for nudging me into supporting steps outcome and conclusion!