adds version update notifications to the step summary and stdout
typesafegithub/github-workflows-kt pull request #1393
Opened 2024-04-18 19:51 UTC by NikkyAI

well here is my first attempt
i tried to leave enough of the API public so that users can use `fun RegularAction<*>.fetchAvailableVersions(): List<Version>` themselves

as well as the github logging (notice, warning, error) and `GITHUB_STEP_SUMMARY` append functions

this wil lalso be useful for iterating on this in workflows without needing to push new versions until we find formatting and such that people are happy with

2024-04-19 12:39 UTC, krzema12 requested changes
Partial review.

2024-04-19 12:39 UTC, krzema12 commented on .jitpack.yml
I moved away from JitPack in favor of Maven snapshots. It's fine for testing, but let's not commit it to the repo.

2024-04-19 12:39 UTC, krzema12 commented on .github/workflows/outdated_workflow.main.kts
Once we test end-to-ensd that stuff works, let's remove this workflow, and instead have some tests lower-level tests.

2024-04-19 12:39 UTC, krzema12 commented on action-versions-updates/build.gradle.kts
> +    // jitpack (or scripting?) seems to have issues when dependencies are coming from a bom
A note to remember using the bom.

2024-04-19 12:39 UTC, krzema12 commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/internal/Http.kt
It's copied from another module - let's try putting it in a shared place, like shared-internal.

2024-04-19 12:39 UTC, krzema12 commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/ActionVersionUpdates.kt
> +    return actionSteps.mapNotNull { step ->
There are no logs as this logic iterates through the actions, and it takes minutes to run.

2024-04-19 12:39 UTC, krzema12 commented on buildSrc/src/main/kotlin/buildsrc/convention/publishing.gradle.kts
> +val jitpack = System.getenv("JITPACK")?.toString()?.toBooleanStrictOrNull() ?: false
Let's also revert these changes.

2024-04-19 12:40 UTC, krzema12 commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/ActionVersionUpdates.kt
> +    return actionSteps.mapNotNull { step ->
It took over 6 minutes to run it, let's try to make it faster. I wonder why it takes so long.

2024-04-20 08:32 UTC, krzema12 commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/internal/Http.kt
I've extracted
```kotlin
suspend fun fetchAvailableVersions(owner: String,name: String,githubToken: String): List<Version>
```

to `shared-internal` module, let's reuse it.

2024-04-20 11:25 UTC, NikkyAI commented on .jitpack.yml
agreed

2024-04-20 11:26 UTC, NikkyAI commented on .github/workflows/outdated_workflow.main.kts
sensible, we could make tests that write the summary to a file and analyze the file content instead if needed

2024-04-20 11:27 UTC, NikkyAI commented on action-versions-updates/build.gradle.kts
> +    // jitpack (or scripting?) seems to have issues when dependencies are coming from a bom
lets hope this was jitpack causing issues and not kotlin-scripting then

2024-04-20 11:32 UTC, NikkyAI commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/ActionVersionUpdates.kt
> +    return actionSteps.mapNotNull { step ->
it does not take that long locally.. i think most of that was waiting on jitpack before the script managed to compile on github actions ?

2024-04-20 11:45 UTC, krzema12 commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/ActionVersionUpdates.kt
> +    return actionSteps.mapNotNull { step ->
Ah, that might be it!

2024-04-20 16:39 UTC, NikkyAI commented on buildSrc/src/main/kotlin/buildsrc/convention/publishing.gradle.kts
> +val jitpack = System.getenv("JITPACK")?.toString()?.toBooleanStrictOrNull() ?: false
some of these are good.. they avoid issues like `Cannot perform signing task ':action-versions-updates:signMavenJavaPublication' because it has no configured signatory`
which happens when you do not have keys set up locally.. lowering the barrier for contributotors

2024-04-20 18:11 UTC, krzema12 commented on buildSrc/src/main/kotlin/buildsrc/convention/publishing.gradle.kts
> +val jitpack = System.getenv("JITPACK")?.toString()?.toBooleanStrictOrNull() ?: false
It doesn't belong to this PR, we can discuss in a separate one.

2024-04-21 11:26 UTC, NikkyAI commented on buildSrc/src/main/kotlin/buildsrc/convention/publishing.gradle.kts
> +val jitpack = System.getenv("JITPACK")?.toString()?.toBooleanStrictOrNull() ?: false
okay, then li will extract it into a seperate branch.. it makes testing this really hard when i cannot `publishToMavenLocal` locally or in actions

2024-04-21 11:37 UTC, NikkyAI commented on buildSrc/src/main/kotlin/buildsrc/convention/publishing.gradle.kts
> +val jitpack = System.getenv("JITPACK")?.toString()?.toBooleanStrictOrNull() ?: false
created a separate PR https://github.com/typesafegithub/github-workflows-kt/pull/1402

2024-04-23 13:12 UTC, krzema12 requested changes
Partial review (but review most of it 😉 ).

2024-04-23 13:12 UTC, krzema12 commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/GithubLogging.kt
Does stuff in this file have to be public? If not, let's make it `internal`.

2024-04-23 13:12 UTC, krzema12 commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/GithubLogging.kt
> +public fun githubError(
Is this function needed? I don't see it being used.

2024-04-23 13:12 UTC, krzema12 commented on action-versions-updates/src/test/kotlin/io/github/typesafegithub/workflows/dsl/CheckVersionsTests.kt
> +class CheckVersionsTests : FunSpec(
The tests are failing, see https://github.com/typesafegithub/github-workflows-kt/actions/runs/8797297289/job/24152141997?pr=1393

2024-04-23 13:12 UTC, krzema12 commented on shared-internal/build.gradle.kts
> +    // note: see https://youtrack.jetbrains.com/issue/KT-67618
```suggestion
    // Note: BOM cannot be used here because this module is a transitive dependency
    // of a module that is used from within Kotlin scripts.
    // See https://youtrack.jetbrains.com/issue/KT-67618
```

2024-04-23 13:12 UTC, krzema12 commented on shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GithubApi.kt
> +        expectSuccess = true
Is it needed (`expectSuccess = true`)? It can break other usages where where I'm trying to avoid exception-driven approach and check for the HTTP status myself.

2024-04-23 13:12 UTC, krzema12 commented on shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GithubApi.kt
> +): String = "https://api.github.com/repos/$owner/${repoName(name)}/git/matching-refs/heads/v"
Why are these changes needed? Perhaps to handle actions that are nested in a repo (e.g. `gradle/actions/setup-gradle`)?

I think I should better document what https://github.com/typesafegithub/github-workflows-kt/blob/fc0930030406b5769068d5283519789350d7add2/shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GithubApi.kt#L15
means in `fetchAvailableVersions`. I think currently the caller is supposed to path a proper repo name, without the directory name (e.g. `actions`, not `actions/setup-gradle`). Could we make it this way so that this piece remains untouched, so that we don't need to test other uses of this util?

2024-04-23 13:12 UTC, krzema12 commented on shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/PathUtils.kt
> +            dotGit.exists() && dotGit.isDirectory()
Why is this change needed?

2024-04-23 13:12 UTC, krzema12 commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/Reporting.kt
> +public fun Workflow.reportAvailableUpdates(
I see two modules exposing public functions: here `Reporting.kt` and `Utils.kt`. Could you describe what's your intended way of using the new module? I mean, we should make the API as simple as possible, perhaps hiding some implementation details as `internal`/`private`.

2024-04-23 13:12 UTC, krzema12 commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/model/RegularActionVersions.kt
> +public data class RegularActionVersions(
Does it need to be public?

2024-04-23 14:08 UTC, NikkyAI commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/GithubLogging.kt
> +public fun githubGroup(
true, i somehow ended up not using it.. this allows you to make a nice folding out section in the logs, do we want to use that ?

2024-04-23 14:43 UTC, NikkyAI commented on shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GithubApi.kt
> +        expectSuccess = true
it is not necessary but then we get back the json error and parsing fails instead in some cryptic way

2024-04-23 14:58 UTC, NikkyAI commented on shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GithubApi.kt
> +): String = "https://api.github.com/repos/$owner/${repoName(name)}/git/matching-refs/heads/v"
yeah, i see now, i am moving the `name.substringBefore('/')` into the calling code instead

2024-04-23 15:01 UTC, NikkyAI commented on shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/PathUtils.kt
> +            dotGit.exists() && dotGit.isDirectory()
it is not, i am not sure why it slipped in.. it makes it more readable though

2024-04-23 15:02 UTC, NikkyAI commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/model/RegularActionVersions.kt
> +public data class RegularActionVersions(
i intended it to be so people could just get a list of available versions and build their own reporting

2024-04-23 15:22 UTC, NikkyAI commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/Reporting.kt
> +public fun Workflow.reportAvailableUpdates(
i did not really spend al ong time thinking about the naming of the modules

but we have the ready to use default `reportVersionUpdates` funtion that is just one call

and the other module is exposed to give consumers the ability to list all available versions and do their own filtering and formatting

if you think we should only expose the minimum required then we can make all the rest internal

2024-04-23 16:52 UTC, krzema12 commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/Utils.kt
> +public fun Workflow.findDependencyDeclaration(action: RegularAction<*>): Pair<Path?, Int?> {
How about making this internal as well? Then the API consists of a single function.

2024-04-23 16:53 UTC, krzema12 commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/Reporting.kt
> +public fun Workflow.reportAvailableUpdates(
Since it will be the only exposed function, could you add some Kdoc putting most focus on what kind of side effects this function has (since it returns nothing)? Like if you were to learn someone how to use the new module, this place is probably the most important one.

2024-04-23 18:31 UTC, NikkyAI commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/Reporting.kt
> +public fun Workflow.reportAvailableUpdates(
will do

2024-04-23 18:32 UTC, NikkyAI commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/Utils.kt
> +public fun Workflow.findDependencyDeclaration(action: RegularAction<*>): Pair<Path?, Int?> {
oh, i overlooked one.. sure can do

2024-04-23 18:53 UTC, krzema12 commented on shared-internal/src/main/kotlin/io/github/typesafegithub/workflows/shared/internal/GithubApi.kt
> +        expectSuccess = true
Ok, let me think about it outside of this PR, thanks for flagging!

2024-04-24 06:24 UTC, krzema12 commented on action-versions-updates/build.gradle.kts
> +    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0")
"we cannot use a BOM" - but it's just a single dependency, why would we need a BOM?

2024-04-24 06:36 UTC, krzema12 commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/Reporting.kt
> + * @param skipAlreadyUpToDate enabled by default, set to false to report when a version is up to date
I'm wondering if we need this param. The goal of this function is to report available updates, so why would someone want to list something more?

2024-04-24 06:36 UTC, krzema12 commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/Utils.kt
> +    onEach: suspend RegularActionVersions.() -> R,
Instead of this param, can we make this function simply accept `RegularActionVersions`, produce a list (or a sequence if needed) and then with `map` do any processing on each?

2024-04-24 06:36 UTC, krzema12 commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/Utils.kt
> +    return runBlocking {
Why is it necessary to block on it? Could we have suspending functions up to a point where the top-level function is a non-suspending one, for the caller's convenience (AFAIK the Kotlin script's entry point is not marked as `suspend`)?

2024-04-24 06:39 UTC, krzema12 commented on action-versions-updates/src/test/kotlin/io/github/typesafegithub/workflows/dsl/CheckVersionsTests.kt
> +class CheckVersionsTests : FunSpec(
Could you rename the file and the class so that it matches the name of the file where the tested function comes from?

2024-04-24 06:39 UTC, krzema12 commented on action-versions-updates/src/test/kotlin/io/github/typesafegithub/workflows/dsl/CheckVersionsTests.kt
> +package io.github.typesafegithub.workflows.dsl
```suggestion
package io.github.typesafegithub.workflows.updates
```

+ please move the file accordingly.

2024-04-24 06:44 UTC, krzema12 commented on action-versions-updates/src/test/kotlin/io/github/typesafegithub/workflows/dsl/CheckVersionsTests.kt
> +class CheckVersionsTests : FunSpec(
This test is failing locally if no token is passed. It's not super-convenient as one has to manually configure the token in multiple Gradle tasks. I'm wondering if we could skip running the tests if `GITHUB_TOKEN` is not set? The tests would still run on CI, and this change would give a smoother experience locally.

2024-04-24 07:19 UTC, NikkyAI commented on action-versions-updates/src/test/kotlin/io/github/typesafegithub/workflows/dsl/CheckVersionsTests.kt
> +class CheckVersionsTests : FunSpec(
my recommendation is to configure the token in your configuration templates, that way any new task run with gradle have those defaults copied over

i am not too familar with kotest and if there is a more convenient way to make tests conditional other than `if(token != null)`

2024-04-24 07:40 UTC, NikkyAI commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/Utils.kt
> +    onEach: suspend RegularActionVersions.() -> R,
much cleaner, good idea

2024-04-24 07:41 UTC, NikkyAI commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/Reporting.kt
> + * @param skipAlreadyUpToDate enabled by default, set to false to report when a version is up to date
lets remove it then

2024-04-24 08:13 UTC, NikkyAI commented on action-versions-updates/src/test/kotlin/io/github/typesafegithub/workflows/dsl/CheckVersionsTests.kt
> +class CheckVersionsTests : FunSpec(
i guess it should be named `ReportingTest` ?

2024-04-24 08:20 UTC, NikkyAI commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/Utils.kt
> +    return runBlocking {
i removed the blocking in that function and move it to the top level function
changing the return type from sequence to flow

2024-04-25 02:20 UTC, NikkyAI commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/GithubLogging.kt
> +public fun githubGroup(
see here: https://github.com/NikkyAI/github-workflows-kt/actions/runs/8816064410/job/24199345944#step:6:19

2024-04-25 02:25 UTC, NikkyAI commented on action-versions-updates/build.gradle.kts
> +    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0")
removed that comment, it was another weirdness coming from a incomplete git merge or rebase i think ?

2024-04-25 06:38 UTC, krzema12 commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/GithubLogging.kt
> +public fun githubGroup(
Ok, looks nice! We could also add "click to unfold", it may be not obvious for users.

2024-04-25 06:39 UTC, krzema12 commented on action-versions-updates/src/main/kotlin/io/github/typesafegithub/workflows/updates/GithubLogging.kt
> +public fun githubError(
It's an internal function, YAGNI - we'll add once needed.

2024-04-25 10:33 UTC, krzema12 commented on .github/workflows/end-to-end-tests.main.kts
> +@file:DependsOn("io.github.typesafegithub:action-versions-updates:1.14.1-SNAPSHOT")
Please add another check here https://github.com/typesafegithub/github-workflows-kt/blob/c677bdfad8e3ff7f4b98d72f22a1ae73650a29b4/github-workflows-kt/build.gradle.kts#L89

2024-04-25 10:58 UTC, NikkyAI commented on .github/workflows/end-to-end-tests.main.kts
> +@file:DependsOn("io.github.typesafegithub:action-versions-updates:1.14.1-SNAPSHOT")
added

2024-04-25 11:55 UTC, NikkyAI commented on .github/workflows/end-to-end-tests.main.kts
> +    if(System.getenv("GHWKT_RUN_STEP") == null) {
that would block people from ever using it in a kotlin logic step ?, unless e add another parameter i guess

2024-04-25 13:14 UTC, krzema12 commented on action-updates-checker/build.gradle.kts
> +    kotlin("plugin.serialization")
Is it needed? I think since GitHub API calls happen in shared-internal now, it should not be needed.

2024-04-25 13:30 UTC, krzema12 approved these changes

2024-04-25 13:36 UTC, krzema12 approved these changes

2024-04-25 13:38 UTC, merged