feat(server): allow to refresh generated artifacts at will
typesafegithub/github-workflows-kt pull request #1598
Opened 2024-08-19 10:01 UTC by Vampire

2024-08-19 10:01 UTC, Vampire commented
* **#1600** <a href="https://app.graphite.dev/github/pr/typesafegithub/github-workflows-kt/1600?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1599** <a href="https://app.graphite.dev/github/pr/typesafegithub/github-workflows-kt/1599?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1598** <a href="https://app.graphite.dev/github/pr/typesafegithub/github-workflows-kt/1598?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Vampire and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-19 15:30 UTC, krzema12 commented on jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
> +            route("/refresh") {
I initially thought that this route just refreshes the cache for a given action, but it actually acts as an alternative repository URL for the scripts. I think it's pretty unsafe. Why: assuming people's good will, someone may just forget to remove the `/refresh` URL suffix, and then each workflow run will result in repopulating cache for all used actions which will put extra load on the server.

What I'd propose instead is to make this endpoint just refresh artifacts for a given action, and return a simple status like `OK` to accompany a HTTP 200 status code. Then it's harder to misuse it, and still possible to refresh desired actions.

2024-08-19 17:17 UTC, Vampire commented
Actually, the main target-use-case was developing changes in the library using hot-swapped changes and then just getting the new result, also putting it to the cache for normal requests.

That it could also be handy for nuking the production cache e.g. if you know there was a new release or changed typings or similar is mainly a positive side-effect.

I changed it now so that for a normal user / production deployment only OK is answered, but you can change it to respond using an environment variable, this can then e.g. be settable when running from IDE.

2024-08-19 17:17 UTC, Vampire commented on jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
> +            route("/refresh") {
Actually, the main target-use-case was developing changes in the library using hot-swapped changes and then just getting the new result, also putting it to the cache for normal requests.

That it could also be handy for nuking the production cache e.g. if you know there was a new release or changed typings or similar is mainly a positive side-effect.

I changed it now so that for a normal user / production deployment only OK is answered, but you can change it to respond using an environment variable, this can then e.g. be settable when running from IDE.

2024-08-23 09:49 UTC, krzema12 requested changes

2024-08-23 09:49 UTC, krzema12 commented on .github/workflows/test-script-consuming-jit-bindings-refresh.main.do-not-compile.kts
> +@file:Repository("http://localhost:8080/refresh/")
I think this script doesn't make much sense because we now disallow using the new endpoint as a repo (at least by default), and this script isn't used in `.github/workflows/bindings-server.main.kts` anyway. Unless you want to test if `GWKT_DELIVER_ON_REFRESH`, but I won't insist on it.

2024-08-23 09:49 UTC, krzema12 commented on jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
> +                }
We currently don't cache whatever is provided by this endpoint, only `{owner}/{name}/{version}/{file}`, so there's no point in refreshing it. However, I see that we want to have in case `GWKT_DELIVER_ON_REFRESH` is enabled. If so, we should guard returning a value from this route as well. See line 98, it's not guarded with `if (refresh && !deliverOnRefreshRoute)`.

2024-08-23 16:40 UTC, Vampire commented on jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
> +                }
How about the very first `if` in `metadata` on line 81?!?

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/tdLND5eJpRKUT3xAEJML/265f5603-d972-48b5-9832-0882374dbdb9.png)

2024-08-23 16:42 UTC, Vampire commented on .github/workflows/test-script-consuming-jit-bindings-refresh.main.do-not-compile.kts
> +@file:Repository("http://localhost:8080/refresh/")
Yeah, definitely, that's just a left-over from the unguarded state.
Now it is removed.

2024-08-23 16:59 UTC, krzema12 commented on jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
> +                }
Right, so we won't return the value - my bad, I misread because my brain was looking for returning "OK" in this case, like we do for the other endpoint. Returning a 404 is a bit confusing. Could we return 200 and OK?

2024-08-23 17:10 UTC, krzema12 commented on jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
> +                }
Sorry, OK doesn't make sense here. Not found is fine. I'm tired today

2024-08-23 17:10 UTC, krzema12 approved these changes

2024-08-23 18:26 UTC, merged