feat(abg)!: provide untyped fields always and typed ones if type available (#1585)
typesafegithub/github-workflows-kt pull request #1603
Opened 2024-08-19 10:01 UTC by Vampire

Fixes #1585

I have to confess, that I did not check every change in the unit test workflow files,
so they should probably be looked again closely. But I think it should have done the right thing.
Or at least how I envisioned it.

no typing =>
- only `_Untyped` class with `_Untyped` properties
- nullability according to requiredness

full typing =>
- same `_Untyped` class as above
- but marked as `@Deprecated` with a replace hint for the typed class (works in the IDE),
- additionally a typed class with each property as typed and untyped version
- all properties nullable, with runtime checks that
  - not the typed and untyped is set both for one property
  - one of the two is set for required properties

partly typing =>
- same `_Untyped` and typed class as above
- for inputs that have no type declared only the `_Untyped` property is added
- the properties that are only untyped have the nullability according to requiredness, also in the typed class

2024-08-19 10:01 UTC, Vampire commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/typesafegithub/github-workflows-kt/1603?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1603** <a href="https://app.graphite.dev/github/pr/typesafegithub/github-workflows-kt/1603?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#1602** <a href="https://app.graphite.dev/github/pr/typesafegithub/github-workflows-kt/1602?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1601** <a href="https://app.graphite.dev/github/pr/typesafegithub/github-workflows-kt/1601?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1600** <a href="https://app.graphite.dev/github/pr/typesafegithub/github-workflows-kt/1600?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1599** <a href="https://app.graphite.dev/github/pr/typesafegithub/github-workflows-kt/1599?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1598** <a href="https://app.graphite.dev/github/pr/typesafegithub/github-workflows-kt/1598?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Vampire and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-21 09:45 UTC, krzema12 requested changes
Impressive, thanks! Just several minor things to discuss/fix.

2024-08-21 09:45 UTC, krzema12 commented on action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/Generation.kt
> +                generateActionBindingSourceCode(
nit: I'm trying to use named arguments to make the call site more readable (even if more verbose). Here I think it will pay off, could you add the names?

2024-08-21 09:45 UTC, krzema12 commented on action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/Generation.kt
> +                .addMember(replaceWith!!)
Shouldn't we configure replacing only if `replaceWith` is non-null? Or actually, I think we can consolidate `deprecated` and `replaceWith` into one (so I think there's no case where the first is true and the second is null). We could name it `replaceWithIfDeprecated across the call stack, then we could get rid of `!!`.

2024-08-21 09:45 UTC, krzema12 commented on action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithAllTypesOfInputs.kt
> +        }
I'd like us to add simple tests for this logic. See e.g. https://github.com/typesafegithub/github-workflows-kt/blob/main/action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithAllTypesOfInputsTest.kt - these are tests that exercise a binding generated in the tests.

I think it's enough to test these two cases:

* the field is typed, and it's required
* the field is typed but it's not required

2024-08-21 09:45 UTC, krzema12 commented on action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/Generation.kt
> +                        "$propertyName or ${propertyName}_Untyped must be set, one of them is required",
```suggestion
                        "Either $propertyName or ${propertyName}_Untyped must be set, one of them is required",
```
to emphasize that it's like logical xor, not or?

2024-08-22 00:04 UTC, Vampire commented on action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/Generation.kt
> +                generateActionBindingSourceCode(
Yeah, definitely.
I usually also do it if it adds significant information.
Here I just moved the snippet you wrote a few lines down, so 🤷‍♂️ 😁

2024-08-22 00:05 UTC, Vampire commented on action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/bindingsfromunittests/ActionWithAllTypesOfInputs.kt
> +        }
Definitely, tests are added

2024-08-22 00:19 UTC, Vampire commented on action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/generation/Generation.kt
> +                .addMember(replaceWith!!)
`replaceWith` is always non-null when that line is reached, as it is expected to put in a `replaceWith` when you give `deprecated = true` but yeah, I can probably combine them, `deprecated` was just there first. :-D

2024-08-22 01:17 UTC, Vampire commented
Additionally to the requested changes I also added a required tag to the KDoc for the cases where nullability does not reflect required status, i.e. in the typed class for typed properties.

2024-08-22 19:33 UTC, krzema12 approved these changes

2024-08-22 19:34 UTC, krzema12 commented
I approved, but it looks like CI didn't run. Any idea why?

2024-08-22 19:50 UTC, merged