feat(server): improve logging setup
typesafegithub/github-workflows-kt pull request #1641
Opened 2024-09-05 21:30 UTC by Vampire

Fixes #1194

2024-09-05 21:31 UTC, Vampire commented
* **#1641** <a href="https://app.graphite.dev/github/pr/typesafegithub/github-workflows-kt/1641?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Vampire and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-21 08:09 UTC, krzema12 requested changes

2024-09-21 08:09 UTC, krzema12 commented on action-binding-generator/build.gradle.kts
> +    implementation("org.apache.logging.log4j:log4j-api:2.24.0")
I'm thinking if we could try out something more kotlinic than the good old log4j, and also multiplatform because it's possible that some of the logic will be executed on a non-JVM platform. E.g. I see that https://github.com/oshai/kotlin-logging is fairly popular, maybe worth giving it a shot?

2024-09-21 08:09 UTC, krzema12 commented on action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/metadata/MetadataReading.kt
> +                logger.atInfo().log("  ... from {}", url)
I don't like the traditional formatting pattern - the Kotlin string template looks nicer. Could we stay with this?

2024-09-21 08:09 UTC, krzema12 commented on jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
> +        .setProperty("java.util.logging.manager", org.apache.logging.log4j.jul.LogManager::class.java.name)
I first see such snippet. Can you explain why it's important? I don't have experience with `java.util.logging.manager`.

2024-09-21 08:09 UTC, krzema12 commented on maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/JarBuilding.kt
> +    check(exitCode == ExitCode.OK) {
Why this change? Seems unrelated.

2024-09-23 09:09 UTC, Vampire commented on action-binding-generator/build.gradle.kts
> +    implementation("org.apache.logging.log4j:log4j-api:2.24.0")
Sure, it's your project. :-)

2024-09-23 09:13 UTC, Vampire commented on action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/metadata/MetadataReading.kt
> +                logger.atInfo().log("  ... from {}", url)
As you also demanded to switch to `kotlin-logging`, sure, there is not much other choice anyway, as that only supports constructing the message in a lambda.

With log4j I would have answered "no", becuase this is not about niceness but about avoiding unnecessary work. There is no point in constructing the actual message if the message is not going to be logged.

That's also one of the points why I don't like `kotlin-logging` in pure JVM project.
Through forcing constructing log messages in the lambda, it at least ensures that it is not constructed if the log level is disabled. But there are so many more reasons why a log message is not needed, for example some filtering by TCM or whatever. But 🤷‍♂️ :-).

2024-09-23 09:17 UTC, Vampire commented on maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/JarBuilding.kt
> +    check(exitCode == ExitCode.OK) {
That's a matter of point-of-view. :-D
Before it was `IllegalArgumentException`, now it is the imho more appropriate here `IllegalStateException`, and you can better read the messages as there is a newline in front of the first compiler message.
This is only shown in the logging - at least currently - so it felt appropriate to included it, as I also fixed it while doing these changes. :-)

2024-09-23 09:35 UTC, Vampire commented on jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
> +        .setProperty("java.util.logging.manager", org.apache.logging.log4j.jul.LogManager::class.java.name)
To capture log messages written using `java.util.logging`, you need to configure a custom log manager.
This is done by setting `java.util.logging.manager` system property.
You can do this of course when calling the JVM using a `-D` parameter, or programmatically.
I usually prefer doing it programmatically as it is then always set and cannot be forgotten, so you get more consistent behavior.
Now with this specific property it is ultra important, that it is set as very first action in the program, because once it was evaluated, changing it has no effect anymore.
Even a simple `private static Whatever foo = ...` can cause some JVM stdlib to do something log-related and thus have this property evaluated.

In a Java application I usually have a `static { ... }` block in the main class above everything else, including static field definitions, so that it definitely is executed as early as possible.

In Kotlin this construct was the closest I could make-up to ensure the same, as with this, the static initializer block of `MainKt` decompiled to Java looks like
```java
static {
   String it = System.setProperty("java.util.logging.manager", LogManager.class.getName());
   int var1 = false;
   logger = KotlinLogging.INSTANCE.logger(MainKt::logger$lambda$1$lambda$0);
   deliverOnRefreshRoute = Boolean.parseBoolean(System.getenv("GWKT_DELIVER_ON_REFRESH"));
}
```

2024-09-23 09:38 UTC, Vampire commented on action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/metadata/MetadataReading.kt
> +                logger.atInfo().log("  ... from {}", url)
As I said, as you demanded `kotlin-logging`, it's irrelevant anyway :-)

2024-10-30 09:47 UTC, krzema12 commented on jit-binding-server/src/main/kotlin/io/github/typesafegithub/workflows/jitbindingserver/Main.kt
> +        .setProperty("java.util.logging.manager", org.apache.logging.log4j.jul.LogManager::class.java.name)
Got it, thanks! TIL.

2024-10-30 09:50 UTC, krzema12 commented on jit-binding-server/src/main/resources/log4j2.xml
> +                <Pattern><![CDATA[%highlight{%d <%-5p> <%-35.35t> <%x> <%X> <%50.50c> %m}%n]]></Pattern>
Do you have a moment to attach a preview of the logging format with this config?

2024-10-30 10:09 UTC, krzema12 commented on jit-binding-server/src/main/resources/log4j2.xml
> +                <Pattern><![CDATA[%highlight{%d <%-5p> <%-35.35t> <%x> <%X> <%50.50c> %m}%n]]></Pattern>
```
 > Task :jit-binding-server:run
 2024-10-30T10:05:27.911880Z main INFO Registered Log4j as the java.util.logging.LogManager.
 2024-10-30 11:05:27,995 <INFO > <main                               > <[]> <{}> <                                  ktor.application> Autoreload is disabled because the development mode is off.
 2024-10-30 11:05:28,033 <INFO > <main                               > <[]> <{}> <                                  ktor.application> Application started in 0.052 seconds.
 2024-10-30 11:05:28,033 <INFO > <main                               > <[]> <{}> <                                  ktor.application> Application started: io.ktor.server.application.Application@569bf9eb
 2024-10-30 11:05:28,103 <INFO > <DefaultDispatcher-worker-1         > <[]> <{}> <                                  ktor.application> Responding at http://0.0.0.0:8080
 2024-10-30 11:05:46,540 <INFO > <eventLoopGroupProxy-4-1            > <[]> <{request-id=3f8wfod3ge25fv3}> <hub.typesafegithub.workflows.jitbindingserver.Main> ➡️ Requesting gradle/actions/setup-gradle@v4
 2024-10-30 11:05:46,555 <INFO > <eventLoopGroupProxy-4-1            > <[]> <{request-id=3f8wfod3ge25fv3}> <ws.actionbindinggenerator.metadata.MetadataReading>   ... from https://raw.githubusercontent.com/gradle/actions/v4/setup-gradle/action.yml
 2024-10-30 11:05:47,239 <INFO > <eventLoopGroupProxy-4-1            > <[]> <{request-id=3f8wfod3ge25fv3}> <flows.actionbindinggenerator.typing.TypesProviding>   ... types from action https://raw.githubusercontent.com/gradle/actions/v4/setup-gradle/action-types.yml
 2024-10-30 11:05:47,440 <INFO > <eventLoopGroupProxy-4-1            > <[]> <{request-id=3f8wfod3ge25fv3}> <flows.actionbindinggenerator.typing.TypesProviding>   ... types from action https://raw.githubusercontent.com/gradle/actions/v4/setup-gradle/action-types.yaml
 2024-10-30 11:05:47,700 <INFO > <eventLoopGroupProxy-4-1            > <[]> <{request-id=3f8wfod3ge25fv3}> <flows.actionbindinggenerator.typing.TypesProviding>   ... types from catalog https://raw.githubusercontent.com/typesafegithub/github-actions-typing-catalog/main/typings/gradle/actions/v4/setup-gradle/action-types.yml
 2024-10-30 11:05:48,004 <INFO > <eventLoopGroupProxy-4-1            > <[]> <{request-id=3f8wfod3ge25fv3}> <flows.actionbindinggenerator.typing.TypesProviding>   ... metadata from https://raw.githubusercontent.com/typesafegithub/github-actions-typing-catalog/main/typings/gradle/actions/metadata.yml
 2024-10-30 11:05:48,335 <INFO > <eventLoopGroupProxy-4-1            > <[]> <{request-id=3f8wfod3ge25fv3}> <flows.actionbindinggenerator.typing.TypesProviding>   ... using fallback version: v3
 2024-10-30 11:05:48,335 <INFO > <eventLoopGroupProxy-4-1            > <[]> <{request-id=3f8wfod3ge25fv3}> <flows.actionbindinggenerator.typing.TypesProviding>   ... types from catalog https://raw.githubusercontent.com/typesafegithub/github-actions-typing-catalog/main/typings/gradle/actions/v3/setup-gradle/action-types.yml
 2024-10-30 11:05:48,799 <INFO > <eventLoopGroupProxy-4-1            > <[]> <{request-id=3f8wfod3ge25fv3}> <                                  ktor.application> 200 OK: GET - /gradle/actions__setup-gradle/v4/actions__setup-gradle-v4.pom in 2278ms
 2024-10-30 11:05:48,880 <INFO > <eventLoopGroupProxy-4-1            > <[]> <{request-id=djvj3l9shgy0ahg}> <                                  ktor.application> 404 Not Found: GET - /favicon.ico in 77ms
```

2024-10-30 10:09 UTC, krzema12 commented on jit-binding-server/src/main/resources/log4j2.xml
> +                <Pattern><![CDATA[%highlight{%d <%-5p> <%-35.35t> <%x> <%X> <%50.50c> %m}%n]]></Pattern>
Good job with request ID, wil let us correlate various logs :)

2024-10-30 10:09 UTC, merged