feat: add permissions to workflow
typesafegithub/github-workflows-kt pull request #743
Opened 2023-04-06 10:25 UTC by benkeil

2023-04-06 17:06 UTC, krzema12 commented
@benkeil please check CI log.

2023-04-06 18:20 UTC, krzema12 commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Workflow.kt
> +        public val actions: PermissionBuilder = of("actions")
We generally try to keep the domain objects free from knowing how to serialize themselves, and serialization is kept in https://github.com/typesafegithub/github-workflows-kt/blob/main/library/src/main/kotlin/io/github/typesafegithub/workflows/yaml/.

2023-04-06 19:09 UTC, krzema12 commented on library/src/test/kotlin/io/github/typesafegithub/workflows/dsl/WorkflowBuilderTest.kt
> +                        Permission.actions.read,
Would it be possible to omit repeating `Permission.`?

2023-04-17 13:13 UTC, benkeil commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Workflow.kt
> +        public val actions: PermissionBuilder = of("actions")
done

2023-04-18 16:18 UTC, krzema12 requested changes

2023-04-18 16:18 UTC, krzema12 commented on library/src/main/kotlin/io/github/typesafegithub/workflows/yaml/ToYaml.kt
> +internal fun Map<Permission, Mode>.mapToYaml() = map { (p, m) -> p.value to m.value }.toMap()
Why not private?

2023-04-18 16:18 UTC, krzema12 commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Workflow.kt
> +public enum class Permission(public val value: String) {
Could you add a link to GitHub docs listing all possible values?

2023-04-18 16:18 UTC, krzema12 commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Workflow.kt
> +    Discussions("discussions"),
If `Discussion`'s order is fixed, then this list will be nicely sorted.

2023-04-18 16:18 UTC, krzema12 commented on library/src/test/kotlin/io/github/typesafegithub/workflows/dsl/WorkflowBuilderTest.kt
> +                            id = "Some-job-1",
There are some unrelated formatting changes in this file, let's revert them.

2023-04-27 04:02 UTC, benkeil commented on library/src/main/kotlin/io/github/typesafegithub/workflows/yaml/ToYaml.kt
> +internal fun Map<Permission, Mode>.mapToYaml() = map { (p, m) -> p.value to m.value }.toMap()
it's also used in `JobsToYaml.kt`

2023-04-27 04:03 UTC, benkeil commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Workflow.kt
> +public enum class Permission(public val value: String) {
done

2023-04-27 04:04 UTC, benkeil commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Workflow.kt
> +    Discussions("discussions"),
done

2023-04-27 04:09 UTC, benkeil commented on library/src/test/kotlin/io/github/typesafegithub/workflows/dsl/WorkflowBuilderTest.kt
> +                            id = "Some-job-1",
done

2023-04-27 04:23 UTC, benkeil commented on library/src/test/kotlin/io/github/typesafegithub/workflows/dsl/WorkflowBuilderTest.kt
> +        context("properties") {
done

2023-04-27 09:26 UTC, krzema12 commented on library/src/test/kotlin/io/github/typesafegithub/workflows/dsl/WorkflowBuilderTest.kt
> +                        job(
There are still some changes in indent. Doesn't your GitHub/git display them? Maybe you have whitespace changes ignoring enabled?

2023-04-27 18:05 UTC, krzema12 requested changes

2023-04-27 18:05 UTC, krzema12 commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Job.kt
> +    val permissions: Map<Permission, Mode>? = null,
We've got the implementation pretty much ready, now it's time to cover it in tests 😄

2023-04-27 20:07 UTC, krzema12 commented on library/src/test/kotlin/io/github/typesafegithub/workflows/IntegrationTest.kt
> +        test("permissions") {
Whenever possible, I try to write tests that are also executed by GitHub. See `testRanWithGitHub`. For this particular change, I think you can piggy-back on an existing test and add some permissions there, so that we don't increase the number of workflows used in tests.

Apart from that, please add unit tests for each layer, they should already be in place for existing logic.

2023-04-30 18:37 UTC, krzema12 commented
@benkeil please sync with the newest main branch - I merged https://github.com/typesafegithub/github-workflows-kt/pull/810, thanks to your proposal!

2023-05-05 17:55 UTC, krzema12 commented on library/src/main/kotlin/io/github/typesafegithub/workflows/yaml/JobsToYaml.kt
> +        "permissions" to permissions?.mapToYaml(),
To cover it in unit tests, we need to modify this test case:

https://github.com/typesafegithub/github-workflows-kt/blob/49a94c09241d430538fd38ed016be2dfcdad07ce/library/src/test/kotlin/io/github/typesafegithub/workflows/yaml/JobsToYamlTest.kt#L106

2023-05-11 19:48 UTC, krzema12 approved these changes

2023-05-11 19:48 UTC, merged