feat(library): Add support for job.container and job.services (#883)
typesafegithub/github-workflows-kt pull request #884
Opened 2023-06-25 18:11 UTC by kugo12

Closes #883

2023-06-25 21:02 UTC, krzema12 requested changes

2023-06-26 15:18 UTC, kugo12 commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Container.kt
> +        public fun healthCheck(
It's helper for docker health check options, commonly used in service containers to wait until "container" is healthy
You can see it used in github service container samples:
- https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers
- https://docs.github.com/en/actions/using-containerized-services/creating-redis-service-containers

2023-06-26 15:35 UTC, kugo12 commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Container.kt
> +    val ports: List<String> = emptyList(),
My reasoning for it was that I wanted to support all possibilities (`8080:80`, `8080:80/tcp`, `8080`, `8080/tcp`)
Maybe `LinkedHashMap<Int, Int?>` with trade-off of not being able to specify protocol this way?

2023-06-26 16:11 UTC, kugo12 commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Container.kt
> +    val volumes: List<String> = emptyList(),
All possibilities based off of [actions source code](https://github.com/actions/runner/blob/5f1c6f4708dc4efeb4afdbda7936537504ef4d33/src/Runner.Worker/Container/ContainerInfo.cs#L295): `source:target`, `target`, `source:target:ro`, `target:ro`
With `LinkedHashMap<String, String>` we could support only 2 of these (first is obvious, second `"source" to "target:ro"`).
Additional note: docker supports more volume options separated by comma, but actions currently supports only `ro`

2023-06-26 17:30 UTC, kugo12 commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Container.kt
> +public data class Container(
Done

2023-06-26 20:58 UTC, krzema12 requested changes

2023-06-26 20:58 UTC, krzema12 commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Container.kt
> +        public fun healthCheck(
Got it, let's leave it then. It would be nice to unit-test it though.

2023-06-26 20:58 UTC, krzema12 commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Container.kt
> +    val ports: List<String> = emptyList(),
Ok, got it. It would be good to support all known possibilities in a type-safe way, including the protocol. Let's brainstorm on a possible API. Maybe the type of this field should be `List<PortMapping>` and then we can have different factory functions:

- `tcp(8080 to 80)`
- `udp(8080 to 80)`
- `tcp(8080)`

or extension property-based, e. g. `(8080 to 80).tcp`. What do you think?

2023-06-26 20:58 UTC, krzema12 commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Container.kt
> +    val volumes: List<String> = emptyList(),
Like with ports, maybe we could make it more type-safe using factory functions? I can imagine e. g. `readOnly("foo" to "bar")` building an object of class `VolumeMapping`, and we would have a list of them here.

2023-06-27 08:13 UTC, kugo12 commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Container.kt
> +    val ports: List<String> = emptyList(),
We would also need an API for specifying port without protocol.

For representing protocol maybe sealed hierarchy with 4 options (all, tcp, udp, custom)?
With api looking like this:
```kotlin
fun port(mapping: Pair<Int, Int>, protocol: PortMapping.Protocol = PortMapping.Protocol.All): PortMapping
fun port(host: Int, protocol: PortMapping.Protocol = PortMapping.Protocol.All): PortMapping
```

2023-06-27 08:25 UTC, kugo12 commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Container.kt
> +    val volumes: List<String> = emptyList(),
I agree, factory functions can make it better

Maybe
```kotlin
fun volume(mapping: Pair<String, String>, isReadOnly: Boolean = false): VolumeMapping
fun volume(target: String, isReadOnly: Boolean = false): VolumeMapping
```
What do you think?

2023-06-27 08:27 UTC, krzema12 commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Container.kt
> +    val ports: List<String> = emptyList(),
Perfect!

2023-06-27 08:27 UTC, krzema12 commented on library/src/main/kotlin/io/github/typesafegithub/workflows/domain/Container.kt
> +    val volumes: List<String> = emptyList(),
Great :)

2023-06-28 09:55 UTC, krzema12 commented on library/src/test/kotlin/io/github/typesafegithub/workflows/domain/ContainerTest.kt
> +            Container.healthCheck(
It all looks cool! I'm just missing one thing: example usage of `Container.healthCheck` within some workflow. Could you maybe add it to ContainerToYamlTest?

2023-06-28 09:55 UTC, krzema12 requested changes
One small thing to address and we're merging.

2023-06-28 10:22 UTC, kugo12 commented on library/src/test/kotlin/io/github/typesafegithub/workflows/domain/ContainerTest.kt
> +            Container.healthCheck(
Sure

2023-06-28 10:26 UTC, krzema12 approved these changes

2023-06-28 10:27 UTC, krzema12 commented
@kugo12 thanks for your contribution and attention to details! I appreciate it.

2023-06-28 10:29 UTC, merged